### ISSUE TITLE
Minimum number of samples required？

### ISSUE THREAD

**Issue by mmmilkbottle** [skgrange/rmweather#5]
Hi,

My data has 110 samples and 9 variables. I used this package to build a prediction model. It is clear and helpful for beginners like me. However, when I used the function: "rmw_calculate_model_errors" to get prediction performance metrics, most of the values looked a little weird (attached below).
mean_bias 33.6, mean_gross_error 559., normalized_mean_bias 0.0162, normalized_mean_gross_error 0.270, root_mean_squared_error 685., normalized_root_mean_squared_error 0.330, r 0.2 48, r_squared 0.0613, p 0.00909, coefficient_of_efficiency 0.0115. I was wondering if is this cause the dataset is not enough to get a good model. Or do you think the values are relatively okay for a model?

Besides the above, I also would like to ask for your help with the metric: FAC2 (fraction of predictions with a factor of two), maybe a bit stupid, I could not find this metric in the model by myself.

Thanks in advance.

Tianci

**Comment by skgrange** [comment]
Hello Tianci,
Good to hear you have found the package easy to use. 

Based on your model error statistics, it looks like you have a very poor model. This is almost certainly related to your dataset only having 110 observations. Usually, this method is used on tens of thousands of observations because the decision tree methods usually such a number of data points to learn how the dataset behaves. So, I think you may need a different approach for your particular set. 

Regarding the fraction of predictions within a factor or two metric, **rmweather** does not calculate this. However, you can use **openair**'s `modStats` function to do this like so: 

```
# Load package
library(openair)

# Calculate fac2
modStats(
  your_data_frame,
  mod = "value_predict",
  obs = "value",
  statistic = "FAC2"
)
```

I hope this helps.
Stuart.

**Comment by mmmilkbottle** [comment]
Hi Stuart,

Got it! Thanks a lot for your clear explanation. 

Cheers,
Tianci
